uv run modal run --detach scripts/modal_train.py -- \
--task format_copy \
--algo reinforce \
--output_dir /vol/runs/modal_format_copy_reinforce \
--steps 51 \
--batch_size 8 \
--group_size 6 \
--min_new_tokens 1 \
--max_new_tokens 24 \
--lr 3e-5 \
--minibatch_size 8 \
--grad_accum_steps 6 \
--kl_coef 0.05 \
--max_grad_norm 0.5 \
--wandb_enabled \
--wandb_project llm-rl-hw4 \
--wandb_name format_copy_reinforce \
--sample_markdown_log_interval 1 \
--sample_log_interval 10 \
--sample_log_n 6 \
--eval_interval 50 \
--save_interval 50 \
--warmup_steps 10