uv run modal run --detach scripts/modal_train.py -- \
--task format_copy \
--algo grpo \
--output_dir /vol/runs/modal_format_copy_grpo_ppo_epochs_5 \
--steps 51 \
--batch_size 8 \
--group_size 6 \
--min_new_tokens 1 \
--max_new_tokens 24 \
--lr 3e-5 \
--ppo_epochs 5 \
--minibatch_size 8 \
--grad_accum_steps 6 \
--clip_eps 0.2 \
--kl_coef 0.05 \
--max_grad_norm 0.5 \
--wandb_enabled \
--wandb_project llm-rl-hw4 \
--wandb_name format_copy_grpo_ppo_epochs_5 \
--sample_markdown_log_interval 1 \
--sample_log_interval 10 \
--sample_log_n 6 \
--eval_interval 50 \
--save_interval 50 \
--warmup_steps 10

uv run modal run --detach scripts/modal_train.py -- \
--task format_copy \
--algo grpo \
--output_dir /vol/runs/modal_format_copy_grpo_kl_coef_001 \
--steps 51 \
--batch_size 8 \
--group_size 6 \
--min_new_tokens 1 \
--max_new_tokens 24 \
--lr 3e-5 \
--ppo_epochs 2 \
--minibatch_size 8 \
--grad_accum_steps 6 \
--clip_eps 0.2 \
--kl_coef 0.01 \
--max_grad_norm 0.5 \
--wandb_enabled \
--wandb_project llm-rl-hw4 \
--wandb_name format_copy_grpo_kl_coef_001 \
--sample_markdown_log_interval 1 \
--sample_log_interval 10 \
--sample_log_n 6 \
--eval_interval 50 \
--save_interval 50 \
--warmup_steps 10

uv run modal run --detach scripts/modal_train.py -- \
--task format_copy \
--algo grpo \
--output_dir /vol/runs/modal_format_copy_grpo_kl_coef_01 \
--steps 51 \
--batch_size 8 \
--group_size 6 \
--min_new_tokens 1 \
--max_new_tokens 24 \
--lr 3e-5 \
--ppo_epochs 2 \
--minibatch_size 8 \
--grad_accum_steps 6 \
--clip_eps 0.2 \
--kl_coef 0.1 \
--max_grad_norm 0.5 \
--wandb_enabled \
--wandb_project llm-rl-hw4 \
--wandb_name format_copy_grpo_kl_coef_01 \
--sample_markdown_log_interval 1 \
--sample_log_interval 10 \
--sample_log_n 6 \
--eval_interval 50 \
--save_interval 50 \
--warmup_steps 10

uv run modal run --detach scripts/modal_train.py -- \
--task format_copy \
--algo grpo \
--output_dir /vol/runs/modal_format_copy_grpo_clip_eps_005 \
--steps 51 \
--batch_size 8 \
--group_size 6 \
--min_new_tokens 1 \
--max_new_tokens 24 \
--lr 3e-5 \
--ppo_epochs 2 \
--minibatch_size 8 \
--grad_accum_steps 6 \
--clip_eps 0.05 \
--kl_coef 0.05 \
--max_grad_norm 0.5 \
--wandb_enabled \
--wandb_project llm-rl-hw4 \
--wandb_name format_copy_grpo_clip_eps_005 \
--sample_markdown_log_interval 1 \
--sample_log_interval 10 \
--sample_log_n 6 \
--eval_interval 50 \
--save_interval 50 \
--warmup_steps 10

uv run modal run --detach scripts/modal_train.py -- \
--task format_copy \
--algo grpo \
--output_dir /vol/runs/modal_format_copy_grpo_grad_accum_steps_1 \
--steps 51 \
--batch_size 8 \
--group_size 6 \
--min_new_tokens 1 \
--max_new_tokens 24 \
--lr 3e-5 \
--ppo_epochs 2 \
--minibatch_size 8 \
--grad_accum_steps 1 \
--clip_eps 0.2 \
--kl_coef 0.05 \
--max_grad_norm 0.5 \
--wandb_enabled \
--wandb_project llm-rl-hw4 \
--wandb_name format_copy_grpo_grad_accum_steps_1 \
--sample_markdown_log_interval 1 \
--sample_log_interval 10 \
--sample_log_n 6 \
--eval_interval 50 \
--save_interval 50 \
--warmup_steps 10